name: Build-Book

on:
  push:
    branches: [ master ]

jobs:      
  deploy:
      runs-on: ubuntu-20.04
      concurrency:
        group: ${{ github.workflow }}-${{ github.ref }}
      steps:
        - uses: actions/checkout@v2

        - name: Setup mdBook
          uses: peaceiris/actions-mdbook@v1
          with:
            mdbook-version: '0.4.12'
            # mdbook-version: 'latest'

        - run: mdbook build
            
        - name: Publish Code
            run: |
              git config --local user.email "github-actions@github.com"
              git config --local user.name "github-actions"
              git add ./book
              git commit -m "🚀 Build latest book" -a
              git push -f
